### ISSUE TITLE
Rozdelovani zaku do trid

### ISSUE THREAD

**Issue by vrka** [epicity-cz/mgraph-cpp#2]
V addschools() region.hpp:1159  https://github.com/epicity-cz/mgraph-cpp/blob/2336b99a19ddffaad6cb2bee663ffd81181a53bf/region.hpp#L1159-L1161 jsou takovy divny kejkle s `+1`.
Predpokladam, ze cilem je rovnomerne rozdelit zaky do trid s max poctem danym konfiguraci.

Takze pro `classsize == 20` to rozdeli 45 studentu `16, 16, 13`. Predpokladam, ze spravne ma byt `15, 15, 15`  nebo je nejaky duvod k tomuto chovani?

**Comment by cyberklezmer** [comment]
Důvod není, alespoň si nepamatuju, že by to tak bylo. Nicméně protože to není závažné (ve skutečnosti jsou třídy jiné), tak to nech pls bejt, kdyžtak si udělej poznámku, a změní se to v druhém běhu.

**Comment by vrka** [comment]
v cpp to neresim, v pythonu to tedy mam opravene

On January 14, 2021 10:49:04 AM GMT+01:00, cyberklezmer <notifications@github.com> wrote:
>Důvod není, alespoň si nepamatuju, že by to tak bylo. Nicméně protože
>to není závažné (ve skutečnosti jsou třídy jiné), tak to nech pls bejt,
>kdyžtak si udělej poznámku, a změní se to v druhém běhu.>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/epicity-cz/mgraph-cpp/issues/2#issuecomment-760084181

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
