### ISSUE TITLE
Bug? distance plosmatrix

### ISSUE THREAD

**Issue by vrka** [epicity-cz/mgraph-cpp#3]
To je schvalne ze meze jsou jen bez posledni "sberne" kategorie? Nebo to ma byt do plosmatrix::numcats()+1?

https://github.com/epicity-cz/mgraph-cpp/blob/2336b99a19ddffaad6cb2bee663ffd81181a53bf/plosmatrix.hpp#L153-L155

podobne v pmtdist, pmdist2

**Comment by cyberklezmer** [comment]
JJ, protože v tom článku je mají pouze do těch osmdesáti, tu sběrnou kategorii nemají...
